### ISSUE TITLE
Include tx.hex in unspents

### ISSUE THREAD

**Issue by msmalley** [sadoprotocol/utxo-api#2]
In most cases, with new BitcoinJS library, you now need to supply the whole TX HEX for non-witness unspents ...

This involves having to do a utxo/transaction on each unspents to get the full tx.hex ...

This could also be added / accessed via an additional parameter?

**Comment by AFwcxx** [comment]
This feature is added in this [commit](https://github.com/sadoprotocol/utxo-api/commit/d571b7882003b1744016b0cf17c55aaef0a13039).

Example of body request:

```json
{
    "address": "<address>",
    "options": {
        "txhex": true // Default: false
    }
}
```
