### ISSUE TITLE
Add rarity filter to safeToSpend unspents

### ISSUE THREAD

**Issue by msmalley** [sadoprotocol/utxo-api#3]
Enable safeToSpend unspents to also be filtered / excluded by a rarity array - such as allow ['common', 'uncommon'] - which would exclude any unspents with ordinals that were not common or uncommon

**Comment by AFwcxx** [comment]
This feature is added in this [commit](https://github.com/sadoprotocol/utxo-api/commit/50104271fb31ee0630cf4ab6b58112dcd62a9eb8).


Example of body request:
```json
{
    "address": "<address>",
    "options": {
        "allowedrarity": ["common", "uncommon"], // Default: ["common", "uncommon"]
    }
}
```

Everything else other than `common` and `uncommon` will be considered **unsafe** to spend.

**Comment by msmalley** [comment]
If I add no extra options / make no changes on my side, does that mean the safeToSpend boolean will already be false by default if it is not common or uncommon?

**Comment by AFwcxx** [comment]
If no changes on `options` on your side, `safeToSpend` will be `false` if the rarity is not `common` or `uncommon`, the entry also will not be displayed unless `options.notsafetospend` is set to `true`

**Comment by msmalley** [comment]
Using this function in Ordit SDK now
